"""Shared data models."""
from dataclasses import dataclass, field, asdict
from enum import Enum
import time


class Speaker(str, Enum):
    """'consultant' = your side (product manager/consultant). 'client' = customer."""
    CONSULTANT = "consultant"
    CLIENT = "client"


@dataclass
class Stakeholder:
    name: str
    role: str = ""
    notes: str = ""          # behavioural observation notes from prior meetings
    mbti: str = ""           # optional weak signal
    is_client: bool = True

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class MeetingContext:
    org_name: str
    objective: str
    session_type: str
    stage: str
    stakeholders: list[Stakeholder] = field(default_factory=list)
    regulatory_frames: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "org_name": self.org_name,
            "objective": self.objective,
            "session_type": self.session_type,
            "stage": self.stage,
            "stakeholders": [s.to_dict() for s in self.stakeholders],
            "regulatory_frames": self.regulatory_frames,
        }


@dataclass
class TranscriptLine:
    """One finalised utterance."""
    text: str
    speaker: Speaker
    speaker_name: str
    ts_start: float          # seconds from session start
    ts_end: float
    confidence: float = 1.0

    def to_dict(self) -> dict:
        d = asdict(self)
        d["speaker"] = self.speaker.value
        return d


@dataclass
class BiomarkerUpdate:
    """A snapshot of biomarker state from Thymia Sentinel.

    Thymia's on_policy_result and on_progress payloads are rich; this is a
    normalised view the frontend renders directly.
    """
    speaker: Speaker
    speaker_name: str
    ts: float
    # Aggregated values where available (0..1 or sigma-from-baseline)
    cognitive_load: float | None = None
    stress: float | None = None
    wellness: float | None = None        # composite — what thymia surfaces
    engagement: float | None = None
    confidence: float | None = None
    # Progress — biomarker collection status (% collected toward trigger window)
    progress: dict[str, float] = field(default_factory=dict)
    raw: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        d = asdict(self)
        d["speaker"] = self.speaker.value
        return d


@dataclass
class Alert:
    """One piece of live intelligence for the consultant dashboard."""
    kind: str                # 'polite-yes' | 'steering' | 'regulatory' | ...
    type: str                # 'critical' | 'warning' | 'coaching' | 'regulatory' | 'value'
    type_label: str
    title: str
    detail: str
    suggestion: str = ""
    suggestion_label: str = ""
    signals: list[dict] = field(default_factory=list)
    source: str = "claude"   # 'claude' | 'thymia' | 'rules'
    ts: float = field(default_factory=time.time)

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class AgentUtterance:
    """A piece of voice-agent speech generated by Claude + rendered by Gradium TTS."""
    text: str
    purpose: str             # 'probe' | 'steer' | 'calm' | 'thought-provoker' | 'summary'
    voice_id: str = ""
    audio_url: str = ""      # where the synthesised audio is served from
    ts: float = field(default_factory=time.time)

    def to_dict(self) -> dict:
        return asdict(self)
